interface objectTypesInterface {
  [key: string]: string;
}

export const userTypes: objectTypesInterface = {
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',

  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',

  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
  LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
};

export const alertTypes: objectTypesInterface = {
  CREATE: 'ALERT_CREATE',
  REMOVE: 'ALERT_REMOVE',
};

export const petsTypes: objectTypesInterface = {
  GET_SUCCESS: 'PETS_GET_SUCCESS',
  GET_FAILURE: 'PETS_GET_FAILURE',
  GET_REQUEST: 'PETS_GET_REQUEST',
};
