export const userTypes = {
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',

  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',

  LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
};
